# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylaunchd < Formula
  desc "A lazygit-style TUI for macOS launchd"
  homepage "https://github.com/na2mene/lazylaunchd"
  version "0.12.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/na2mene/lazylaunchd/releases/download/v0.12.0/lazylaunchd_0.12.0_darwin_amd64.tar.gz"
    sha256 "72b15829e2a0231edb42033e7007ee5aaead97089f7d7a7f893e937184009fee"

    define_method(:install) do
      bin.install "lazylaunchd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/na2mene/lazylaunchd/releases/download/v0.12.0/lazylaunchd_0.12.0_darwin_arm64.tar.gz"
    sha256 "5018806d07cdcb712bf6e53eeef5c2240578fd67a8438aa843e8b09c34f74b13"

    define_method(:install) do
      bin.install "lazylaunchd"
    end
  end

  test do
    system "#{bin}/lazylaunchd", "--version"
  end
end
