# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylaunchd < Formula
  desc "A lazygit-style TUI for macOS launchd"
  homepage "https://github.com/na2mene/lazylaunchd"
  version "0.16.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/na2mene/lazylaunchd/releases/download/v0.16.0/lazylaunchd_0.16.0_darwin_amd64.tar.gz"
    sha256 "025dd89ad4bd8201e1ac47763ccba20dd1d24d13cffbbe50b259464281c0f86c"

    define_method(:install) do
      bin.install "lazylaunchd"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/na2mene/lazylaunchd/releases/download/v0.16.0/lazylaunchd_0.16.0_darwin_arm64.tar.gz"
    sha256 "8b788b9cfc90768ada0d960ec80569a6e813196188ac5c001d4993b566868157"

    define_method(:install) do
      bin.install "lazylaunchd"
    end
  end

  def caveats
    <<~EOS
      To finish setup, run:
        lazylaunchd setup
      This installs the background watcher — it records run history and
      sends a macOS notification when a job fails, even while the TUI
      is closed. Re-run it after upgrades. Remove it anytime from the
      TUI (Delete on com.lazylaunchd.watcher).
    EOS
  end

  test do
    system "#{bin}/lazylaunchd", "--version"
  end
end
